INSERT INTO department (name)
VALUES  ("Human Resources")  
        ("Marketing")
        ("Sales")
        ("Information Technology")
        ("Administrative",)



INSERT INTO title_role (title, salary, department_id)
VALUES  ("Sales Executive", 65k, 3)
        ("Sales Manager", 85k, 3)
        ("Resources Assistant", 50k, 1)
        ("Resources Manager", 85k, 1)
        ("Marketing Lead", 95k, 2)
        ("Technology Assistant", 120k, 4)
        ("Database Technologist", 175k, 4)
        ("Technology Manger", 220k, 4)
        ("Operations Manager", 195k, 5)
        ("Director of IT & HR ", 750k, 5)
        ("CFO of M&S", 1m, 5)
        ("Ceo", 6m, 5)

INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES  ("David", "Niven" 6, 12)
        ("George", "Lazenby" 6, 12)
        ("Geoffrey", "Holder" 6, 12)
        ("Mads", "Mikkelsen" 6, 12)
        ("Gert", "Frobe" 6, 12)
        ("Richard", "Kiel" 6, 12)
        ("Timothy", "Dalton" 6, 12)
        ("Christopher", "Walken" 6, 12)
        ("Roger", "Moore" 6, 12)
        ("Daniel", "Craig" 6, 12)
        ("Pierce", "Brosnan" 6, 12)
        ("Shawn", "Connery" 6, 12)

