INSERT INTO cms (department, title, first_name, last_name, salary)
VALUES  ("Human Resources", 6, 12)  
        ("Finance", 3, 3)
        ("Marketing", 10, 20)
        ("Sales", 10, 30)
        ("Production", 5, 5)
        ("Information Technology" 4, 7)
        ("Operations", 7, 7)
        ("Administrative", 5, 8)
        ("Accounting", 5, 5)
        ("Purchasing", 3, 5)
